// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawdsfsakmhpsonddmxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd2RzZnNha21ocHNvbmRkbXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTMzOTksImV4cCI6MjA3MzE4OTM5OX0.HzK7BMeupVS6RJuKVCT4W9edNzQD1dJq5rf5ofy6QAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});